### ISSUE TITLE
error in redcap_entity_v2.3.6 line 44

### ISSUE THREAD

**Issue by pbchase** [ctsit/redcap_entity#35]
Steve Boren reports:

![Screen Shot 2022-01-28 at 8 56 35 AM](https://user-images.githubusercontent.com/3356493/151559175-7b11b82e-3021-4fba-8c8c-06dfa70679b1.png)

Here's the text of his error message:

```
Error message: Uncaught Exception: Invalid entity type. in modules/redcap_entity_v2.3.6/classes/EntityList.php:44 Stack trace: 
#0 modules/project_ownership_v2.0.3/plugins/admin_ownership_list.php(7): REDCapEntity\EntityList->__construct('project_ownersh...', Object(ProjectOwnership\ExternalModule\ExternalModule)) 
#1 redcap_v12.1.2/ExternalModules/index.php(126): require('m...') 
#2 {main} thrown
File: modules/redcap_entity_v2.3.6/classes/EntityList.php
Line: 44
```

**Comment by ChemiKyle** [comment]
@mbentz-uf this is possibly related to #33
